### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by qyh214** [Helias/Keira2#1]
1, multi language support, provide Lang options, easy to localize.
2, e.g:item: class subclass, spellid column should have the pop option, easy to search skills, class,subclass ……you can refer to Truice
3, to provide add new items, new creature options (now only to maintain)
Expect to become a web version of the Truice!

**Comment by ShinDarth** [comment]
@qyh214  thanks for using Keira2 and for posting your suggestions!

about suggestion 1) are you sure we need that? Keira has not so many strings, and even if we translate Keira in different languages, it would be hard to work on the database for ones who don't know english, because the trinitycore database documentation is written in english.

about suggestion 2) @Helias already though to implement those kind of features (so I assigned him this issue)

about suggestion 3) I'm not sure to understand what do you mean, can you give more details?

however at the moment we are working to implement the SmartAI editor on Keira too, so we are a bit busy now and we can't implement other things fastly, but feel free to suggest more ideas!

**Comment by Helias** [comment]
Implemented in release 2.2.1
